name: Merge to gh-pages and build

on:
  push:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    
    - name: Set Git config
      run: |
          git config --local user.email "actions@github.com"
          git config --local user.name "Github Actions"

    - name: Backmerge to gh-pages
      run: |
        git fetch --unshallow
        git checkout gh-pages
        git pull
        git merge --no-ff master -m "Auto merge master to gh-pages branch"
        git push

    - name: Build 
      run: | 
        npm install
        npm run build
        mv /home/runner/work/DLBIPMI01-Frontend/docs/browser/* home/runner/work/DLBIPMI01-Frontend/docs/
        cp /home/runner/work/DLBIPMI01-Frontend/docs/index.html home/runner/work/DLBIPMI01-Frontend/docs/404.html
        
