name: NodeJS with Webpack

on:
  push:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Build
      run: |
        git fetch --unshallow
        git checkout gh-pages
        git pull
        git merge --no-ff master -m "Auto merge master to gh-pages branch"
        npm install
        npm build --output-path docs --base-href /DLBIPMI01-Frontend/
        mv /docs/browser/* /docs/
        cp /docs/index.html /docs/404.html
        
